name: update tag job

on:
  workflow_call:

jobs:
  find-and-replace-with-new-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Find and Replace srep1
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: refs/tags/[/_A-Za-z\d\.-]+
          replace: refs/tags/newTag
          include: src/test/resources/*
          exclude: .github/**
