name: After PR is merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: print some variables
        run: |
          echo The PR was merged
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${{GITHUB_REF#refs/*/}}
          echo $(git tag --oneline)
      - name: read commits
        shell: bash
        run: |
          echo 'COMMITS<<EOF' >> $env:GITHUB_ENV
#          git log "v0.0.1..HEAD" --oneline >> $env:GITHUB_ENV
          echo 'hehe' >> $env:GITHUB_ENV
          echo 'EOF' >> $env:GITHUB_ENV
      - name: print env var
        shell: bash
        run: |
          echo "${{ env.COMMITS }}"
