name: After PR is merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - run: |
          echo The PR was merged
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${GITHUB_REF#refs/*/}
          echo ${{ git tag }}
          echo $(git tag)
#          echo "TAG_NAME=$(git tag)" >> $GITHUB_ENV
#          echo $TAG_NAME
#          git describe --tags --abbrev=0
