name: After PR is merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${GITHUB_REF#refs/*/}