name: After PR is merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@main
        with:
          ref: special-branch
      - name: read commits
        run: |
          echo 'COMMITS<<EOF' >> $GITHUB_ENV
          git log a32aebc..HEAD --oneline >> $GITHUB_ENV
          echo 'hehe' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: print env var
        run: |
          echo "${{ env.COMMITS }}"