name: Find string in a file

on:
  workflow_dispatch:

jobs:
  find-string-in-file:
    runs-on: ubuntu-latest
    steps:
      - name: Find string
        run: |
          python --version
          echo pwd
          pwd
          ls ./scripts
          python scripts/searchLatestTagInChangelog.py CHANGELOG.md
          
  
