name: Find string in a file

on:
  workflow_dispatch:

jobs:
  find-string-in-file:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Find string
        run: |
          python --version
          python scripts/searchLatestTagInChangelog.py CHANGELOG.md
          
  
