name: Find string in a file

on:
  workflow_dispatch:

jobs:
  find-string-in-file:
    runs-on: ubuntu-latest
    steps:
      - name: print current dir
        shell: cmd
        run: |
          echo pwd
          pwd
          echo ls
          ls
      - name: Find string
        run: |
          python --version
          python scripts/searchLatestTagInChangelog.py CHANGELOG.md
          
  
