name: Find string in a file

on:
  workflow_dispatch:

jobs:
  find-string-in-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find string
        run: |
          python --version
          python scripts/searchLatestTagInChangelog.py CHANGELOG.md
          
  
