name: Read latest tag from CHANGELOG

on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        type: string
        description: 'Runner for the workflow'
      repo:
        type: string
        required: false
        default: wilhelmhuang/project1
        description: 'Repository from which the changelog file will be read'
      branch:
        type: string
        required: false
        default: master
        description: 'Branch from which the changelog file will be read'

jobs:
  read-latest-tag-job:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    outputs:
      latest_tag: ${{ steps.regex_match.outputs.group1 }}
    steps:
      # check out repository
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}

      # read changelog file
      - name: Read file contents
        id: read_changelog
        uses: andstor/file-reader-action@v1
        with:
          path: "CHANGELOG.md"

      # find latest tag in changelog file
      - name: Find latest tag in CHANGELOG
        id: regex_match
        uses: actions-ecosystem/action-regex-match@v2.0.2
        with:
          text: ${{ steps.read_changelog.outputs.contents }}
          regex: '30.08.2023'

      - name: print out tag
        run: |
          echo "hello world!"
          echo ${{ steps.regex_match.outputs.group1 }}
          echo "bye bye!"
