name: Test reading current tag from changelog
on:
  workflow_dispatch:

jobs:
  job1:
    uses: wilhelmhuang/weihuang/.github/workflows/07-read-current-tag-from-changelog.yml@master
    with:
      branch: 'special-branch'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.current_tag }}