name: Test set env variables
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value on ubuntu
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value on ubuntu
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

  job2:
    runs-on: windows-latest
    steps:
      - name: Set the value on windows
        id: step_one
        run: |
          echo "color_1=yellow" >> "$GITHUB_OUTPUT"
          echo "color_2=red" >> "$GITHUB_OUTPUT"
      - name: Use the value on windows
        id: step_two
        run: |
          printf '%s\n' ${{ steps.step_one.outputs.color_1}}
          printf '%s\n' ${{ steps.step_one.outputs.color_2}}
