name: Test env variables
on:
  workflow_dispatch:

jobs:
  job:
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_REF: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
        - run: echo "$REPO_NAME"
        - run: echo "$GITHUB_REF"