name: Test getting branch name
on:
  workflow_dispatch:

jobs:
  job1:
    uses: wilhelmhuang/weihuang/.github/workflows/05-get-branch-name.yml@master
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.branch_name }}